### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Dyoung-1** [jwxa2015/MongoDB-HoneyProxyPy#1]
Hi, I have run your program. When the client connects, it can print the connection information, but then it will disconnect and report an error.  please help me   
![image](https://user-images.githubusercontent.com/55119665/64748849-2368ab80-d546-11e9-8667-fe600c907613.png)
![image](https://user-images.githubusercontent.com/55119665/64748856-26fc3280-d546-11e9-8d55-da78d8517de7.png)

**Comment by qboy1987** [comment]
sorry, i didn't run on windows, u can debug it and pr to me。or you can run this on docker
