### ISSUE TITLE
opCode

### ISSUE THREAD

**Issue by Dyoung-1** [jwxa2015/MongoDB-HoneyProxyPy#2]
你好，我想问下为什么不管是做删除还是查询操作 mongo发过来的opcode 解析出来都是2004，都是一样的   ，@jwxa2015
![image](https://user-images.githubusercontent.com/55119665/64773878-b70d9c80-d585-11e9-8f9e-85cee2969b1e.png)

**Comment by qboy1987** [comment]
op_code代码不是数据包的最前部分，你可以参考：https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/
其解析是在_parse_data方法中，你可以试着把每个数据包完整的打出来，也有可能会不会是被包装在查询语句里，这个我之后我再去验证一下。

**Comment by qboy1987** [comment]
我也很奇怪为什么会有这种问题，当时我是参考那个nodejs的代码来写的，也是参考那个网址中的定义来做的。我一开始解析出query命令，我以为就成功了，但是其他并没有去好好测试，非常抱歉。但是在数据包中发现了insert和delete 字符。等我找到真实的包结构的时候我再修改这个问题。
再次感谢所提的问题。

**Comment by qboy1987** [comment]
已添加新的解析。
